cd ..;
#python main.py --dataset-path "/users/local/datasets/" --dataset miniimagenet --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/mini.pt1" --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 9292819
#python main.py --dataset-path "/users/local/datasets/" --dataset cifarfs --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/cifarWeightCE3.pt1" --weightCE --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 292819282;
#python main.py --dataset-path "/users/local/datasets/" --dataset cifarfs --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/cifarWeightCE4.pt1" --weightCE --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 192837291;
#python main.py --dataset-path "/users/local/datasets/" --dataset cifarfs --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/cifarWeightCE5.pt1" --weightCE --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 739282918;
#python main.py --dataset-path "/users/local/datasets/" --dataset cifarfs --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/cifar7WeightCE.pt1" --weightCE --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 897138918;
#python main.py --dataset-path "/users/local/datasets/" --dataset cifarfs --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/cifar8.pt1" --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 604683841;
python main.py --dataset-path "/users/local/datasets/" --dataset miniimagenet --model resnet12 --epochs 0 --manifold-mixup 500 --rotations --cosine --gamma 0.9 --milestone 100 --batch-size 128 --preprocessing "ME" --n-shots 1 --skip-epochs 450 --save-model "/users/local/y17bendo/backbones/miniCorrupted.pt1" --wandb "brain-imt" --wandbProjectName "fewShotY" --seed 727718812;


