
mkdir /ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/;

python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS0backbone11.pt' --seed 989898;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS1backbone11.pt' --seed 898989;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS2backbone11.pt' --seed 767676;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS3backbone11.pt' --seed 676767;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS4backbone11.pt' --seed 656565;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS5backbone11.pt' --seed 565656;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS6backbone11.pt' --seed 545454;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS7backbone11.pt' --seed 454545;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS8backbone11.pt' --seed 434343;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS9backbone11.pt' --seed 343434;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS10backbone11.pt' --seed 323232;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS11backbone11.pt' --seed 232323;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS12backbone11.pt' --seed 212121;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS13backbone11.pt' --seed 121212;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS14backbone11.pt' --seed 919191;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS15backbone11.pt' --seed 191919;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS16backbone11.pt' --seed 828282;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS17backbone11.pt' --seed 282828;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS18backbone11.pt' --seed 737373;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS19backbone11.pt' --seed 373737;
python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 50 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/AS1000/miniAS20backbone11.pt' --seed 646464;

# python main.py --dataset-path '/home/y17bendo/Documents/datasets/' --dataset miniimagenet --model resnet12 --batch-size 128 --epochs 0 --load-model '/ssd2/backbones/resnet12/miniimagenet/mini1.pt1' --n-augmentation 2 --save-augmented-features '/ssd2/data/AugmentedSamples/features/miniImagenet/CropsAS200/CropsAS200_miniAS0backbone11.pt' --seed 989898;

